stages:
  - test
m3lint:
  services:
    - docker:dind
  tags:
    - m3lint
  stage: test
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN master3.takima.io:4567
    - docker run --read-only -v $(pwd)/:/tmp/milestone master3.takima.io:4567/master3/tools/m3-lint -d /tmp/milestone